imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@FootbelAPIBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    serializer:
        enabled: true
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    assets:
        roboto-bold-ttf:
            inputs: '@FootbelBackendBundle/Resources/public/materialize-src/font/roboto/Roboto-Bold.ttf'
            output: 'font/roboto/Roboto-Bold.ttf'
        roboto-bold-woff:
            inputs: '@FootbelBackendBundle/Resources/public/materialize-src/font/roboto/Roboto-Bold.woff'
            output: 'font/roboto/Roboto-Bold.woff'
        roboto-bold-woff2:
            inputs: '@FootbelBackendBundle/Resources/public/materialize-src/font/roboto/Roboto-Bold.woff2'
            output: 'font/roboto/Roboto-Bold.woff2'
        roboto-light-ttf:
            inputs: '@FootbelBackendBundle/Resources/public/materialize-src/font/roboto/Roboto-Light.ttf'
            output: 'font/roboto/Roboto-Light.ttf'
        roboto-light-woff:
            inputs: '@FootbelBackendBundle/Resources/public/materialize-src/font/roboto/Roboto-Light.woff'
            output: 'font/roboto/Roboto-Light.woff'
        roboto-light-woff2:
            inputs: '@FootbelBackendBundle/Resources/public/materialize-src/font/roboto/Roboto-Light.woff2'
            output: 'font/roboto/Roboto-Light.woff2'
        roboto-medium-ttf:
            inputs: '@FootbelBackendBundle/Resources/public/materialize-src/font/roboto/Roboto-Medium.ttf'
            output: 'font/roboto/Roboto-Medium.ttf'
        roboto-medium-woff:
            inputs: '@FootbelBackendBundle/Resources/public/materialize-src/font/roboto/Roboto-Medium.woff'
            output: 'font/roboto/Roboto-Medium.woff'
        roboto-medium-woff2:
            inputs: '@FootbelBackendBundle/Resources/public/materialize-src/font/roboto/Roboto-Medium.woff2'
            output: 'font/roboto/Roboto-Medium.woff2'
        roboto-regular-ttf:
            inputs: '@FootbelBackendBundle/Resources/public/materialize-src/font/roboto/Roboto-Regular.ttf'
            output: 'font/roboto/Roboto-Regular.ttf'
        roboto-regular-woff:
            inputs: '@FootbelBackendBundle/Resources/public/materialize-src/font/roboto/Roboto-Regular.woff'
            output: 'font/roboto/Roboto-Regular.woff'
        roboto-regular-woff2:
            inputs: '@FootbelBackendBundle/Resources/public/materialize-src/font/roboto/Roboto-Regular.woff2'
            output: 'font/roboto/Roboto-Regular.woff2'
        roboto-thin-ttf:
            inputs: '@FootbelBackendBundle/Resources/public/materialize-src/font/roboto/Roboto-Thin.ttf'
            output: 'font/roboto/Roboto-Thin.ttf'
        roboto-thin-woff:
            inputs: '@FootbelBackendBundle/Resources/public/materialize-src/font/roboto/Roboto-Thin.woff'
            output: 'font/roboto/Roboto-Thin.woff'
        roboto-thin-woff2:
            inputs: '@FootbelBackendBundle/Resources/public/materialize-src/font/roboto/Roboto-Thin.woff2'
            output: 'font/roboto/Roboto-Thin.woff2'
        material-design-icons-eot:
            inputs: '@FootbelBackendBundle/Resources/public/materialize-src/font/material-design-icons/Material-Design-Icons.eot'
            output: 'font/material-design-icons/Material-Design-Icons.eot'
        material-design-icons-svg:
            inputs: '@FootbelBackendBundle/Resources/public/materialize-src/font/material-design-icons/Material-Design-Icons.svg'
            output: 'font/material-design-icons/Material-Design-Icons.svg'
        material-design-icons-ttf:
            inputs: '@FootbelBackendBundle/Resources/public/materialize-src/font/material-design-icons/Material-Design-Icons.ttf'
            output: 'font/material-design-icons/Material-Design-Icons.ttf'
        material-design-icons-woff:
            inputs: '@FootbelBackendBundle/Resources/public/materialize-src/font/material-design-icons/Material-Design-Icons.woff'
            output:
        material-design-icons-woff2:
            inputs: '@FootbelBackendBundle/Resources/public/materialize-src/font/material-design-icons/Material-Design-Icons.woff2'
            output: 'font/material-design-icons/Material-Design-Icons.woff2'
    filters:
        cssrewrite: ~
        sass: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
fos_rest:
    versioning: true
    view:
        view_response_listener: 'force'
        formats:
            json: true
        empty_content: 204
    param_fetcher_listener: true
    body_listener: true
    format_listener:
        rules:
            - { path: ^/api, priorities: [ json ], fallback_format: json, prefer_extension: true }
            - { path: ^/, priorities: ['html', '*/*'], fallback_format: html, prefer_extension: true }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: KevinVR\FootbelBackendBundle\Entity\User

old_sound_rabbit_mq:
    connections:
        default:
            host:     "%rabbitmq_host%"
            port:     "%rabbitmq_port%"
            user:     "%rabbitmq_user%"
            password: "%rabbitmq_pass%"
            vhost:    "%rabbitmq_vhost%"
            lazy:     true
            connection_timeout: 3
            read_write_timeout: 3

            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: false

            # requires php-amqplib v2.4.1+
            heartbeat: 0
    producers:
        process_resource:
            auto_setup_fabric: false
            connection:       default
            exchange_options: {name: 'process-resource', type: direct}
    consumers:
        process_resource:
            auto_setup_fabric: false
            connection:       default
            exchange_options: {name: 'process-resource', type: direct}
            queue_options:    {name: 'process-resource'}
            callback:         process_resource_service
