footbel_api:
    resource: "@FootbalistoAPIBundle/Resources/config/routing.yml"
    type:     rest
    prefix:   /api

footbel_processor:
    resource: "@FootbalistoProcessorBundle/Controller/"
    type:     annotation
    prefix:   /process

footbel_backend:
    resource: "@FootbalistoBackendBundle/Controller/"
    type:     annotation
    prefix:   /admin

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"