footbel_processor:
    resource: "@FootbelProcessorBundle/Controller/"
    type:     annotation
    prefix:   /process

footbel_backend:
    resource: "@FootbelBackendBundle/Controller/"
    type:     annotation
    prefix:   /admin

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"