footbel_frontend:
    resource: "@FootbelFrontendBundle/Controller/"
    type:     annotation
    prefix:   /

footbel_api:
    resource: "@FootbelAPIBundle/Resources/config/routing.yml"
    type:     rest
    prefix:   /api

footbel_processor:
    resource: "@FootbelProcessorBundle/Controller/"
    type:     annotation
    prefix:   /process

footbel_backend:
    resource: "@FootbelBackendBundle/Controller/"
    type:     annotation
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"