# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    process_resource_service:
        class: KevinVR\FootbalistoProcessorBundle\Processor\ResourceProcessorConsumer
        arguments:
            rabbitWorker: "@rabbit_worker"
            entityManager: "@doctrine.orm.entity_manager"

    rabbit_worker:
        class: KevinVR\FootbalistoProcessorBundle\Processor\ResourceQueueWorkerRabbitMQ
        arguments:
            rabbitProducer: "@old_sound_rabbit_mq.process_resource_producer"

    app.token_authenticator:
            class: KevinVR\FootbalistoAPIBundle\Security\TokenAuthenticator
            arguments: ['@doctrine.orm.entity_manager']

    google_analytics:
        class: KevinVR\FootbalistoAPIBundle\Service\GoogleAnalyticsService
        arguments: ['@service_container']
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
