<?php

namespace KevinVR\FootbalistoBackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceRepository extends EntityRepository
{
    public function findResourcesToProcess()
    {
        $dt = new \DateTime();

        $criteria = new \Doctrine\Common\Collections\Criteria();
        $criteria
            ->where($criteria->expr()->lt('checked', $dt->sub(new \DateInterval('PT2H'))))
            ->andWhere($criteria->expr()->isNull('queued'));

        $results = $this->matching($criteria);

        return $results;
    }
}
